### ISSUE TITLE
Consider centosbuild/centos7 as the base image

### ISSUE THREAD

**Issue by fedorov** [modelhub-ai/modelhub-engine#11]
Advantage: it is maintained, includes build tools, and is under 300M

https://github.com/dockcross/centos-build/blob/master/centos7/Dockerfile
https://hub.docker.com/r/centosbuild/centos7/

**Comment by fedorov** [comment]
Updated location of the repo above: https://github.com/dockbuild/dockbuild

**Comment by fedorov** [comment]
I just noticed ubuntu base images were added to dockbuild

**Comment by michaelschwier** [comment]
I checked our current docker. The ubuntu plus the build tools we need is below 250MB, what makes it large are the specific libs/frameworks we need, so in terms of size the dockbuild images are not better. We can still discuss if it's worth switching, but since our current setup is running well, I'd consider it low priority for now and focus on other more urgent things first

**Comment by michaelschwier** [comment]
Keeping ubuntu base image for now, since it doesn't seem to have any downsides (see above), has worked flawlessly up to now, and we're used to it by now :)
